[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xidlehook core library"
edition = "2018"
license = "MIT"
name = "xidlehook-core"
version = "0.3.0"

repository = "https://gitlab.com/jD91mZM2/xidlehook"
readme = "README.md"
keywords = ["xorg", "x", "timer"]
categories = ["date-and-time"]

[dependencies]
async-std = { version = "1.2.0", optional = true }
log = "0.4.8"
nix = "0.15.0"
structopt = "0.3.5"
xcb = { version = "0.9.0", features = ["x11", "screensaver"] }
tokio = { version = "1.3.0", optional = true, features = ["time"] }

[dependencies.libpulse-binding]
optional = true
version = "2.14.0"
default-features = false
features = ["pa_v12"]

[dev-dependencies]
env_logger = "0.7.1"

[features]
default = ["pulse"]
pulse = ["libpulse-binding"]

[package.metadata.deb]
name = "xidlehook-core"
maintainer = "jD91mZM2 <me@krake.one>"
extended-description = """\
xidlehook is a general-purpose replacement for xautolock.
this is the core library
"""
depends = "$auto, ,libxcb1, libpulse0"
section = "utils"
priority = "optional"
